---

- name: Exc 3c
  hosts: localhost
  gather_facts: False
  tasks:
    - debug:
        var: ansible_host

- name: Exc 3c Cisco
  hosts: cisco
  gather_facts: False
  tasks:
    - debug:
        var: ansible_connection
    - debug:
        var: ansible_host  
